### PR TITLE
added custom schemas support

### PR DESCRIPTION
**Pull request by ElSergioKra**
Added custom schemas support.

### CODE REVIEW

**Comment by maszuDEV** [comment]
Hi @fnando, is there any chance to merge this PR in the near future? Is very helpful

**Comment by fnando** [comment]
Sorry for not taking a look sooner.

This pr's implementation is broken right now (not the feature, but the pr; GH Action was wrong and not running tests on all pull requests.)

Additionally, I think we shouldn't always dump the schema name; instead, let's check the default search path and only include it when the schema is not in the default path.

I made all these changes on #11. Let me know what do you think about these changes.

**Comment by ElSergioKra** [comment]
Yes, you're right. We don't need the schema name if it is in the search path.

**Comment by fnando** [comment]
Closed via #11

**Comment by fnando** [comment]
Just released v0.2.1 with this change.

**Pull request closed without merging**
